apiVersion: v1
kind: Pod
metadate:
  name: hello-world
spec:
  containers:
  - name: hello-world
    image: us.irc.io/<my_namespace>/hello-world:1
    ports:
    - containerPort: 8080
  imagePullSecrets:
  - name: irc